version: "3.9"
services:
  build:
    image: emscripten/emsdk:2.0.15
    user: "${_UID}:${_GID}"
    volumes:
      - .:/exec
    working_dir: /exec
    entrypoint: ["sh", "./build.sh"]
  serve:
    image: python:3.9.2
    user: "${_UID}:${_GID}"
    volumes:
      - .:/exec
    ports:
      - "8000:8000"
    working_dir: /exec
    entrypoint: ["sh", "./run.sh"]
